/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppGoalsRouteImport } from './routes/app.goals'
import { Route as AppFinancesRouteImport } from './routes/app.finances'
import { Route as AppFamilyRouteImport } from './routes/app.family'
import { Route as AppBudgetRouteImport } from './routes/app.budget'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppFinancesIdRouteImport } from './routes/app.finances.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancesRoute = AppFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AppRoute,
} as any)
const AppFamilyRoute = AppFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetRoute = AppBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancesIdRoute = AppFinancesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppFinancesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/budget': typeof AppBudgetRoute
  '/app/family': typeof AppFamilyRoute
  '/app/finances': typeof AppFinancesRouteWithChildren
  '/app/goals': typeof AppGoalsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/finances/$id': typeof AppFinancesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/budget': typeof AppBudgetRoute
  '/app/family': typeof AppFamilyRoute
  '/app/finances': typeof AppFinancesRouteWithChildren
  '/app/goals': typeof AppGoalsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/finances/$id': typeof AppFinancesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/budget': typeof AppBudgetRoute
  '/app/family': typeof AppFamilyRoute
  '/app/finances': typeof AppFinancesRouteWithChildren
  '/app/goals': typeof AppGoalsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/finances/$id': typeof AppFinancesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/app/analytics'
    | '/app/budget'
    | '/app/family'
    | '/app/finances'
    | '/app/goals'
    | '/app/settings'
    | '/app/'
    | '/app/finances/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/app/analytics'
    | '/app/budget'
    | '/app/family'
    | '/app/finances'
    | '/app/goals'
    | '/app/settings'
    | '/app'
    | '/app/finances/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/app/analytics'
    | '/app/budget'
    | '/app/family'
    | '/app/finances'
    | '/app/goals'
    | '/app/settings'
    | '/app/'
    | '/app/finances/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goals': {
      id: '/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finances': {
      id: '/app/finances'
      path: '/finances'
      fullPath: '/app/finances'
      preLoaderRoute: typeof AppFinancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/family': {
      id: '/app/family'
      path: '/family'
      fullPath: '/app/family'
      preLoaderRoute: typeof AppFamilyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/budget': {
      id: '/app/budget'
      path: '/budget'
      fullPath: '/app/budget'
      preLoaderRoute: typeof AppBudgetRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finances/$id': {
      id: '/app/finances/$id'
      path: '/$id'
      fullPath: '/app/finances/$id'
      preLoaderRoute: typeof AppFinancesIdRouteImport
      parentRoute: typeof AppFinancesRoute
    }
  }
}

interface AppFinancesRouteChildren {
  AppFinancesIdRoute: typeof AppFinancesIdRoute
}

const AppFinancesRouteChildren: AppFinancesRouteChildren = {
  AppFinancesIdRoute: AppFinancesIdRoute,
}

const AppFinancesRouteWithChildren = AppFinancesRoute._addFileChildren(
  AppFinancesRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBudgetRoute: typeof AppBudgetRoute
  AppFamilyRoute: typeof AppFamilyRoute
  AppFinancesRoute: typeof AppFinancesRouteWithChildren
  AppGoalsRoute: typeof AppGoalsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBudgetRoute: AppBudgetRoute,
  AppFamilyRoute: AppFamilyRoute,
  AppFinancesRoute: AppFinancesRouteWithChildren,
  AppGoalsRoute: AppGoalsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
